version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - CONFIG=container
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_HOST=%
    volumes:
      - data:/var/lib/mysql
volumes:
  data: {}